#!/bin/bash
#PBS -N parco-job
#PBS -o ./out-parco
#PBS -e ./err-parco
#PBS -q short_cpuQ
#PBS -l walltime=0:10:00
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=1gb

module load gcc91
module load mpich-3.2.1--gcc-9.1.0
module load python-3.10.14
export OMP_NUM_THREADS=64
cd PARCO
make all

if [ -z "$flags" ]; then
  echo "Flags are not set, running full benchmark"
  mpirun ./bin/out --benchmark-full
else
  mpirun ./bin/out $flags
fi
